config/routes.rb
Hati::Application.routes.draw do

  devise_for :users
  root :to => 'manager/gos#index'

  match 'go/:code', :to => 'go#index'
  match 'j/:code', :to => 'go#index'
  # match 'shorten', :to => 'go#shorten', :as => :shorten_url

  namespace :manager do
    resources :gos do
      resources :access_logs
    end

    resources :gos, :access_logs
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/go.rb
class Go < ActiveRecord::Base
  has_many :access_logs
  attr_accessible :code, :url, :sina_weibo_shorten_url, :is_monitoring, :monitor_group_name

  validates :code, uniqueness: true
  # validates :url, uniqueness: true
  # validates :sina_weibo_shorten_url, uniqueness: true

  before_validation :strip_whitespace, :only => [:code, :url]

  private
  def strip_whitespace
    self.code = self.code.strip
    self.url = self.url.strip
  end
end

app/controllers/go_controller.rb
class GoController < ApplicationController
  layout 'go'

  def index
    go = Go.find_by_code params[:code]
    render and return if go.nil?
    AccessLog.create!({
      header: request.env.to_s,
      referal: request.env["HTTP_REFERER"],
      remote_ip: request.env["REMOTE_ADDR"],
      go_code: params[:code],
      go_id: go.id,
      real_ip: request.env["HTTP_X_REAL_IP"],
      forwarded_for: request.env["HTTP_X_FORWARDED_FOR"]
    })

    @go_url = go.url
  end

  def shorten
    if request.post?
      @go = Go.find_by_code params[:shorten][:code]
      api = SinaWeibo::Api::ShortenUrlRequest.new '2.00bA8_nBoJOHoD35177487ac7atD1E'
      result = api.shorten "http://go.sptida.com/go/#{code}"
      @go.sina_weibo_shorten_url = result['urls'][0]['url_short']
      @go.save
    end
  end
end

app/controllers/manager/access_logs_controller.rb
class Manager::AccessLogsController < ApplicationController
  # GET /manager/access_logs
  # GET /manager/access_logs.json
  def index
    if params[:go_id]
      @access_logs_grid = initialize_grid(AccessLog.where(go_id: params[:go_id]).order("created_at DESC"))
      @go = Go.find params[:go_id]
    else
      @access_logs_grid = initialize_grid(AccessLog.order("created_at DESC"))
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @access_logs_grid }
    end
  end

  # GET /manager/access_logs/1
  # GET /manager/access_logs/1.json
  def show
    @access_log = AccessLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @access_log }
    end
  end

  # GET /manager/access_logs/new
  # GET /manager/access_logs/new.json
  def new
    @access_log = AccessLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @access_log }
    end
  end

  # GET /manager/access_logs/1/edit
  def edit
    @access_log = AccessLog.find(params[:id])
  end

  # POST /manager/access_logs
  # POST /manager/access_logs.json
  def create
    @access_log = AccessLog.new(params[:access_log])

    respond_to do |format|
      if @access_log.save
        format.html { redirect_to manager_access_log_path(@access_log), notice: 'Access log was successfully created.' }
        format.json { render json: @access_log, status: :created, location: @access_log }
      else
        format.html { render action: "new" }
        format.json { render json: @access_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manager/access_logs/1
  # PATCH/PUT /manager/access_logs/1.json
  def update
    @access_log = AccessLog.find(params[:id])

    respond_to do |format|
      if @access_log.update_attributes(params[:access_log])
        format.html { redirect_to manager_access_log_path(@access_log), notice: 'Access log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @access_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manager/access_logs/1
  # DELETE /manager/access_logs/1.json
  def destroy
    @access_log = AccessLog.find(params[:id])
    @access_log.destroy

    respond_to do |format|
      format.html { redirect_to manager_access_logs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/manager/gos_controller.rb
class Manager::GosController < ApplicationController
  before_filter :authenticate_user!

  # GET /manager/gos
  # GET /manager/gos.json
  def index
    @gos_grid = initialize_grid(Go)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gos_grid }
    end
  end

  # GET /manager/gos/1
  # GET /manager/gos/1.json
  def show
    @go = Go.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @go }
    end
  end

  # GET /manager/gos/new
  # GET /manager/gos/new.json
  def new
    @go = Go.new
    code = RandomAlphaGenerator.generate
    while Go.find_by_code(code)
      code = RandomAlphaGenerator.generate
    end
    @go.code = code

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @go }
    end
  end

  # GET /manager/gos/1/edit
  def edit
    @go = Go.find(params[:id])
  end

  # POST /manager/gos
  # POST /manager/gos.json
  def create
    @go = Go.new(params[:go])
    api = SinaWeibo::Api::UrlShortener.new Settings.app.sina_weibo_access_token
    @go.sina_weibo_shorten_url = api.shorten "#{request.protocol}#{request.host_with_port}/go/#{@go.code}"

    respond_to do |format|
      if @go.save
        format.html { redirect_to manager_gos_path(), notice: 'Go was successfully created.' }
        format.json { render json: @go, status: :created, location: @go }
      else
        format.html { render action: "new" }
        format.json { render json: @go.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manager/gos/1
  # PATCH/PUT /manager/gos/1.json
  def update
    @go = Go.find(params[:id])
    @go.code = params[:go][:code]
    @go.url = params[:go][:url]
    if @go.code_changed?
      api = SinaWeibo::Api::UrlShortener.new Settings.app.sina_weibo_access_token
      @go.sina_weibo_shorten_url = api.shorten "#{request.protocol}#{request.host_with_port}/go/#{@go.code}"
    end

    respond_to do |format|
      if @go.save
        format.html { redirect_to manager_gos_path(), notice: 'Go was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @go.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manager/gos/1
  # DELETE /manager/gos/1.json
  def destroy
    @go = Go.find(params[:id])
    @go.destroy

    respond_to do |format|
      format.html { redirect_to manager_gos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/go_helper.rb
module GoHelper
end

app/helpers/manager/access_logs_helper.rb
module Manager::AccessLogsHelper
end

app/helpers/manager/gos_helper.rb
module Manager::GosHelper
end

app/views/manager/gos/_form.html.erb
<%= simple_form_for( ['manager', @go], :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="control-group url optional go_result_url"><label class="url optional control-label" for="go_result_url">Result url</label><div class="controls"><%= "#{request.protocol}#{request.host_with_port}/go/#{@go.code}" %></div></div>

    <%= f.input :code %>
    <%= f.input :url %>
    <%= f.input :monitor_group_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'button button-primary' %>
  </div>
<% end %>

app/views/manager/gos/edit.html.erb
<%= render_page_title "#{t('model.edit', model: Go.model_name.human)} <small>#{t('simple_form.required.text') }</small>" do |toolbar|
  toolbar << {
    name: "#{t('labels.back_to')}#{t('model.list', :model => Go.model_name.human)}",
    url: manager_gos_path,
    options: {class: 'button'}
  }
  end %>
<%= render 'form' %>

app/views/manager/gos/index.html.erb
<%= render_page_title "#{t('model.list', model: Go.model_name.human)}" do |toolbar|
  toolbar << {
    name: render_icon_and_text_content('icon-plus-sign', t('model.create', :model => Go.model_name.human)),
    url: new_manager_go_path,
    options: {class: 'button button-primary'}
  }
end %>

<%= grid(@gos_grid, :show_filters => :always) do |g|

  g.column name: t('activerecord.attributes.go.code') do |go|
    link_to go.code, "#{request.protocol}#{request.host_with_port}/go/#{go.code}", target: 'blank'
  end

  g.column name: t('activerecord.attributes.go.url') do |go|
    link_to go.url, go.url, target: 'blank'
  end

  g.column name: t('activerecord.attributes.go.sina_weibo_shorten_url') do |go|
    link_to go.sina_weibo_shorten_url, go.sina_weibo_shorten_url, target: 'blank'
  end

  g.column name: t('activerecord.attributes.go.access_logs_count') do |go|
    link_to go.access_logs.count, manager_go_access_logs_path(go)
  end

  g.column name: t('activerecord.attributes.go.monitor_group_name') do |go|
    go.monitor_group_name
  end

  g.column :html => {class: 'buttons'} do |go|
    link_to(render_icon_content('icon-edit'), edit_manager_go_path(go), :class => 'button', :rel => 'tooltip', :title => t('buttons.edit'))
  end

  g.column :html => {class: 'buttons'} do |go|
    link_to(render_icon_content('icon-trash'), manager_go_path(go), :method => :delete, :confirm => t("confirms.delete"), :class => 'button', :rel => 'tooltip', :title => t('buttons.delete'))
  end
end -%>

app/views/manager/gos/new.html.erb
<%= render_page_title "#{t('model.create', model: Go.model_name.human)} <small>#{t('simple_form.required.text') }</small>" do |toolbar|
  toolbar << {
    name: "#{t('labels.back_to')}#{t('model.list', :model => Go.model_name.human)}",
    url: manager_gos_path,
    options: {class: 'button'}
  }
  end %>
<%= render 'form' %>

app/views/manager/gos/show.html.erb
<%= render_page_title "#{@go.name}" do |toolbar|
  toolbar << {
    name: "#{t('labels.back_to')}#{t('model.list', :model => Go.model_name.human)}",
    url: gos_path,
    options: {class: 'button'}
  }
end %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>
        属性
      </th>
      <th>
        值
      </th>
    </tr>
  </thead>
  <tbody>
      </tbody>
  <tfoot>

  </tfoot>
</table>